# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdpress < Formula
  desc "Markdown to PDF presentation tool"
  homepage "https://github.com/Skel-Tech/mdpress"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.3/mdpress_0.1.3_darwin_amd64.tar.gz"
      sha256 "015b0595561c64751d0a5324477294479b4b3b4cc7783b91d929ea74bbf3874d"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.3/mdpress_0.1.3_darwin_arm64.tar.gz"
      sha256 "79125adfb99062365d6e841f9c1645f16a9c1bb659cced1676a746b54f4c1995"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.3/mdpress_0.1.3_linux_amd64.tar.gz"
      sha256 "a64d1d51d41451e2f6eae0a3b27613d2295f91c3d9c0a00998f8ee10eb744ae0"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.3/mdpress_0.1.3_linux_arm64.tar.gz"
      sha256 "b29088e1929eafd98338e2f6bdfd335084ca94140539f34ba6a58ed711cbc02c"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  test do
    system "#{bin}/mdpress", "version"
  end
end
