# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdpress < Formula
  desc "Markdown to PDF presentation tool"
  homepage "https://github.com/Skel-Tech/mdpress"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.0/mdpress_0.1.0_darwin_amd64.tar.gz"
      sha256 "4bba3c30b41a853fd79bdbc2788cb95ed8f3ce32473748ebd4ea1bd82b8cf4b5"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.0/mdpress_0.1.0_darwin_arm64.tar.gz"
      sha256 "10ff65d7f25964d0e323a5f5ab4e87be9164d80494559c20b6810165e61ef6d0"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.0/mdpress_0.1.0_linux_amd64.tar.gz"
      sha256 "2643de29101cae789ab97d728b07351bd9d9e94743846a3385df2eecb927f625"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skel-Tech/mdpress/releases/download/v0.1.0/mdpress_0.1.0_linux_arm64.tar.gz"
      sha256 "8296fc765e9de1fd92b36029f50363d6ac382df8c05ad435b1da736942c9b43b"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  test do
    system "#{bin}/mdpress", "version"
  end
end
